layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      - taylorcaton.github.io2
      - react-blog-test

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: taylorcaton
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: taylorc
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Sonic Pi
    web_url: https://sonic-pi.net/
    image_url: https://sonic-pi.net/media/images/home/logo.png

  - name: Reason
    web_url: https://www.propellerheads.com/en/reason
    image_url: https://cdn.freebiesupply.com/logos/large/2x/reason-1-logo-png-transparent.png

  - name: Vue
    web_url: https://vuejs.org/
    image_url: https://vuejs.org/images/logo.png
